# Generated by Django 5.0.7 on 2024-07-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_img',
            field=models.ImageField(null=True, upload_to='course_images'),
        ),
    ]
